ALTER TABLE UTENTI_CONFIG
ADD FLGADMINCONFIG SMALLINT DEFAULT 0;

COMMENT ON COLUMN UTENTI_CONFIG.FLGADMINCONFIG IS
'flag utente configuratore dei menu amministratore';

/******************************************************************************/
/*                 Generated by IBExpert 29/10/2025 14:22:42                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE PARAMETRI (
    CODPAR  VARCHAR(15) NOT NULL,
    DESPAR  VARCHAR(255),
    NOTE    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GRUPPO  CHAR(20)
);




/******************************************************************************/
/*                                Primary Keys                                */
/******************************************************************************/

ALTER TABLE PARAMETRI ADD CONSTRAINT PK_PARAMETRI PRIMARY KEY (CODPAR);


/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON PARAMETRI TO PUBLIC;
GRANT SELECT ON PARAMETRI TO TABX;


INSERT INTO PARAMETRI (CODPAR, DESPAR, NOTE, GRUPPO) VALUES ('DBVERSION', '0.0.0', NULL, NULL);