-- For manual upgrades from schema 1.3.0. The built-in updater applies these changes idempotently.
ALTER TABLE UTENTI_CONFIG ADD FLGPWDLESS SMALLINT DEFAULT 0 NOT NULL;
CREATE TABLE ACCESSI_2FA (
  CHALLENGE_ID VARCHAR(64) CHARACTER SET ASCII NOT NULL PRIMARY KEY,
  CODUTE INTEGER NOT NULL REFERENCES UTENTI (CODUTE) ON DELETE CASCADE,
  EMAIL VARCHAR(254) CHARACTER SET UTF8 NOT NULL,
  AUTHMODE VARCHAR(12) CHARACTER SET ASCII NOT NULL,
  IDNKEY VARCHAR(64) CHARACTER SET ASCII,
  CODEHASH VARCHAR(64) CHARACTER SET ASCII NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  EXPIRES_AT TIMESTAMP NOT NULL,
  SENT_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ATTEMPTS SMALLINT DEFAULT 0 NOT NULL,
  SENDS SMALLINT DEFAULT 1 NOT NULL
);
CREATE INDEX IDX_ACCESSI_2FA_USER ON ACCESSI_2FA (CODUTE, CREATED_AT);
CREATE INDEX IDX_ACCESSI_2FA_EXP ON ACCESSI_2FA (EXPIRES_AT);
