/** Minimum schema owned by Accessi. Application columns and catalog rows are deliberately absent. */
export interface SchemaTable {
  columns: Record<string, string>;
  primaryKey: string[];
}

export const ACCESSI_SCHEMA_VERSION = '1.6.0';
export const ACCESSI_VERSION_KEY = 'AccessiVersion';

export const accessiTables: Record<string, SchemaTable> = {
  PARAMETRI: { columns: { CODPAR: 'VARCHAR(15) NOT NULL', DESPAR: 'VARCHAR(255)', NOTE: 'BLOB SUB_TYPE 1', GRUPPO: 'VARCHAR(20)' }, primaryKey: ['CODPAR'] },
  UTENTI: { columns: {
    CODUTE: 'INTEGER NOT NULL', USRNAME: 'VARCHAR(100)', FLGGDPR: 'SMALLINT DEFAULT 0', DATGDPR: 'DATE',
    DATINS: 'DATE', DATSCAPWD: 'DATE', DATLASTLOGIN: 'DATE', STAREG: 'SMALLINT DEFAULT 0', KEYREG: 'VARCHAR(100)',
  }, primaryKey: ['CODUTE'] },
  UTENTI_CONFIG: { columns: {
    CODUTE: 'INTEGER NOT NULL', COGNOME: 'VARCHAR(50)', NOME: 'VARCHAR(50)', AVATAR: 'VARCHAR(30)',
    FLG2FATT: 'SMALLINT DEFAULT 0', FLGPWDLESS: 'SMALLINT DEFAULT 0 NOT NULL', FLGPASSWORD: 'SMALLINT DEFAULT 1 NOT NULL',
    CODLINGUA: "VARCHAR(2) DEFAULT 'IT'", FLGSUPER: 'SMALLINT DEFAULT 0', FLGADMINCONFIG: 'SMALLINT DEFAULT 0',
    CELLULARE: 'VARCHAR(15)', PAGDEF: 'VARCHAR(50)', JSON_METADATA: 'BLOB SUB_TYPE 1',
  }, primaryKey: ['CODUTE'] },
  UTENTI_PWD: { columns: { CODUTE: 'INTEGER NOT NULL', PWD: 'VARCHAR(255)' }, primaryKey: ['CODUTE'] },
  UTENTI_OLDPWD: { columns: { CODUTE: 'INTEGER NOT NULL', OLDPWD: 'VARCHAR(255)' }, primaryKey: ['CODUTE'] },
  UTENTI_GDPR: { columns: { CODUTE: 'INTEGER NOT NULL', DATACC: 'DATE NOT NULL', GDPR: 'VARCHAR(2000)' }, primaryKey: ['CODUTE', 'DATACC'] },
  RUOLI: { columns: { CODRUO: 'INTEGER NOT NULL', DESRUO: 'VARCHAR(30)' }, primaryKey: ['CODRUO'] },
  MENU_GRP: { columns: { CODGRP: 'VARCHAR(1) NOT NULL', DESGRP: 'VARCHAR(100)', FLGENABLED: 'SMALLINT DEFAULT 0', ORDINE: 'SMALLINT DEFAULT 0', NOMECAMPO: 'VARCHAR(20)' }, primaryKey: ['CODGRP'] },
  MENU_TIPI: { columns: { CODTIP: 'VARCHAR(1) NOT NULL', DESTIP: 'VARCHAR(20)' }, primaryKey: ['CODTIP'] },
  MENU: { columns: {
    CODMNU: 'VARCHAR(20) NOT NULL', DESMNU: 'VARCHAR(100)', CODGRP: 'VARCHAR(1) NOT NULL', FLGENABLED: 'INTEGER DEFAULT 0',
    ICON: 'VARCHAR(50)', ORDINE: 'SMALLINT', CODTIP: 'VARCHAR(1)', PAGINA: 'VARCHAR(50)', RIFMENU: 'VARCHAR(20)', NOTE: 'VARCHAR(1000)',
  }, primaryKey: ['CODMNU'] },
  ABILITAZIONI: { columns: { CODUTE: 'INTEGER NOT NULL', CODMNU: 'VARCHAR(20) NOT NULL', TIPABI: 'SMALLINT DEFAULT 0' }, primaryKey: ['CODUTE', 'CODMNU'] },
  RUOLI_MNU: { columns: { CODRUO: 'INTEGER NOT NULL', CODMNU: 'VARCHAR(20) NOT NULL', TIPABI: 'SMALLINT' }, primaryKey: ['CODRUO', 'CODMNU'] },
  UTENTI_RUOLI: { columns: { CODUTE: 'INTEGER NOT NULL', CODRUO: 'INTEGER NOT NULL' }, primaryKey: ['CODUTE', 'CODRUO'] },
  FILTRI_TIPO: { columns: { TIPFIL: 'SMALLINT NOT NULL', DESFIL: 'VARCHAR(20)', FLDFIL: 'VARCHAR(20)', FLGENABLED: 'SMALLINT DEFAULT 1 NOT NULL' }, primaryKey: ['TIPFIL'] },
  FILTRI: { columns: { CODUTE: 'INTEGER NOT NULL', PROG: 'INTEGER NOT NULL', TIPFIL: 'SMALLINT' }, primaryKey: ['CODUTE', 'PROG'] },
  SSO_PROVIDER: { columns: {
    PROVIDER: 'VARCHAR(64) CHARACTER SET ASCII NOT NULL', DESCRIZIONE: 'VARCHAR(160) CHARACTER SET UTF8 NOT NULL',
    FLGATTIVO: 'SMALLINT DEFAULT 1 NOT NULL', DATINS: 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL', NOTA: 'VARCHAR(500) CHARACTER SET UTF8',
  }, primaryKey: ['PROVIDER'] },
  UTENTI_IDENTITA_EXT: { columns: {
    IDNKEY: 'CHAR(64) CHARACTER SET ASCII NOT NULL', CODUTE: 'INTEGER NOT NULL', PROVIDER: 'VARCHAR(64) CHARACTER SET ASCII NOT NULL',
    SUBJECT: 'VARCHAR(512) CHARACTER SET UTF8 NOT NULL', FLGATTIVO: 'SMALLINT DEFAULT 1 NOT NULL',
    DATINS: 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL', DATLASTLOGIN: 'TIMESTAMP', DATDISATT: 'TIMESTAMP', NOTA: 'VARCHAR(500) CHARACTER SET UTF8',
  }, primaryKey: ['IDNKEY'] },
  ACCESSI_2FA: { columns: {
    CHALLENGE_ID: 'VARCHAR(64) CHARACTER SET ASCII NOT NULL', CODUTE: 'INTEGER NOT NULL', EMAIL: 'VARCHAR(254) CHARACTER SET UTF8 NOT NULL',
    AUTHMODE: 'VARCHAR(12) CHARACTER SET ASCII NOT NULL', IDNKEY: 'VARCHAR(64) CHARACTER SET ASCII', CODEHASH: 'VARCHAR(64) CHARACTER SET ASCII NOT NULL',
    CREATED_AT: 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL', EXPIRES_AT: 'TIMESTAMP NOT NULL', SENT_AT: 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL',
    ATTEMPTS: 'SMALLINT DEFAULT 0 NOT NULL', SENDS: 'SMALLINT DEFAULT 1 NOT NULL',
  }, primaryKey: ['CHALLENGE_ID'] },
  // Token di servizio (macchina-a-macchina). Il segreto non e mai salvato in chiaro: TOKEN_HASH
  // contiene lo SHA-256 del segreto, confrontato a tempo costante in fase di verifica.
  ACCESSI_SERVICE_TOKEN: { columns: {
    TOKEN_ID: 'VARCHAR(40) CHARACTER SET ASCII NOT NULL', TOKEN_HASH: 'VARCHAR(64) CHARACTER SET ASCII NOT NULL',
    LABEL: 'VARCHAR(100) CHARACTER SET UTF8', SCOPES: 'VARCHAR(500) CHARACTER SET ASCII', CREATED_BY: 'INTEGER',
    CREATED_AT: 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL', EXPIRES_AT: 'TIMESTAMP', LAST_USED_AT: 'TIMESTAMP', REVOKED_AT: 'TIMESTAMP',
  }, primaryKey: ['TOKEN_ID'] },
};

export const accessiForeignKeys = [
  { name: 'FK_ABILITAZIONI_1', table: 'ABILITAZIONI', column: 'CODMNU', target: 'MENU', targetColumn: 'CODMNU' },
  { name: 'FK_MENU_1', table: 'MENU', column: 'CODGRP', target: 'MENU_GRP', targetColumn: 'CODGRP' },
  { name: 'FK_MENU_2', table: 'MENU', column: 'CODTIP', target: 'MENU_TIPI', targetColumn: 'CODTIP' },
  { name: 'FK_RUOLI', table: 'UTENTI_RUOLI', column: 'CODRUO', target: 'RUOLI', targetColumn: 'CODRUO', cascade: true },
  { name: 'FK_UTENTI', table: 'UTENTI_RUOLI', column: 'CODUTE', target: 'UTENTI', targetColumn: 'CODUTE', cascade: true },
  { name: 'FK_UTEIDEXT_UTENTE', table: 'UTENTI_IDENTITA_EXT', column: 'CODUTE', target: 'UTENTI', targetColumn: 'CODUTE', cascade: true },
  { name: 'FK_UTEIDEXT_PROVIDER', table: 'UTENTI_IDENTITA_EXT', column: 'PROVIDER', target: 'SSO_PROVIDER', targetColumn: 'PROVIDER' },
  { name: 'FK_ACCESSI_2FA_USER', table: 'ACCESSI_2FA', column: 'CODUTE', target: 'UTENTI', targetColumn: 'CODUTE', cascade: true },
];

export const accessiIndexes = [
  { name: 'IDX_UTEIDEXT_CODUTE', table: 'UTENTI_IDENTITA_EXT', columns: ['CODUTE'] },
  { name: 'IDX_UTEIDEXT_PROVIDER', table: 'UTENTI_IDENTITA_EXT', columns: ['PROVIDER'] },
  { name: 'IDX_ACCESSI_2FA_USER', table: 'ACCESSI_2FA', columns: ['CODUTE', 'CREATED_AT'] },
  { name: 'IDX_ACCESSI_2FA_EXP', table: 'ACCESSI_2FA', columns: ['EXPIRES_AT'] },
];

export const accessiChecks = [
  { name: 'CK_SSO_PROVIDER_ATTIVO', table: 'SSO_PROVIDER', expression: 'FLGATTIVO IN (0, 1)' },
  { name: 'CK_UTEIDEXT_ATTIVO', table: 'UTENTI_IDENTITA_EXT', expression: 'FLGATTIVO IN (0, 1)' },
];

export const accessiTriggers = [
  { name: 'UTENTI_BI', table: 'UTENTI', type: 1, event: 'BEFORE INSERT', body: 'AS BEGIN IF (NEW.CODUTE IS NULL) THEN NEW.CODUTE = GEN_ID(GEN_UTENTI_ID, 1); NEW.DATINS = CURRENT_TIMESTAMP; END' },
  { name: 'RUOLI_BI', table: 'RUOLI', type: 1, event: 'BEFORE INSERT', body: 'AS BEGIN IF (NEW.CODRUO IS NULL) THEN NEW.CODRUO = GEN_ID(GEN_RUOLI_ID, 1); END' },
  { name: 'FILTRI_BI0', table: 'FILTRI', type: 1, event: 'BEFORE INSERT', body: 'AS DECLARE VARIABLE TOT INTEGER; BEGIN IF (NEW.PROG IS NULL) THEN BEGIN SELECT COALESCE(MAX(PROG), 0) FROM FILTRI WHERE CODUTE = NEW.CODUTE INTO :TOT; NEW.PROG = TOT + 1; END END' },
  { name: 'UTENTI_GDPR_BI0', table: 'UTENTI_GDPR', type: 1, event: 'BEFORE INSERT', body: 'AS BEGIN NEW.DATACC = CURRENT_TIMESTAMP; UPDATE UTENTI SET FLGGDPR = 1, DATGDPR = CURRENT_TIMESTAMP WHERE CODUTE = NEW.CODUTE; END' },
];

export const accessiGenerators = [
  { name: 'GEN_UTENTI_ID', table: 'UTENTI', column: 'CODUTE' },
  { name: 'GEN_RUOLI_ID', table: 'RUOLI', column: 'CODRUO' },
];
