-- Generic Accessi schema 1.5.0 for an EMPTY, already-created Firebird database (3.0+).
-- For existing databases use AccessiDatabaseUpdater.run: this snapshot is not an upgrade script.
-- No users, menus, filter catalogs, application columns, credentials or grants are provisioned.
SET SQL DIALECT 3;

CREATE TABLE PARAMETRI (
    CODPAR VARCHAR(15) NOT NULL,
    DESPAR VARCHAR(255),
    NOTE BLOB SUB_TYPE 1,
    GRUPPO VARCHAR(20)
);

ALTER TABLE PARAMETRI ADD CONSTRAINT PK_PARAMETRI PRIMARY KEY (CODPAR);

CREATE TABLE UTENTI (
    CODUTE INTEGER NOT NULL,
    USRNAME VARCHAR(100),
    FLGGDPR SMALLINT DEFAULT 0,
    DATGDPR DATE,
    DATINS DATE,
    DATSCAPWD DATE,
    DATLASTLOGIN DATE,
    STAREG SMALLINT DEFAULT 0,
    KEYREG VARCHAR(100)
);

ALTER TABLE UTENTI ADD CONSTRAINT PK_UTENTI PRIMARY KEY (CODUTE);

CREATE TABLE UTENTI_CONFIG (
    CODUTE INTEGER NOT NULL,
    COGNOME VARCHAR(50),
    NOME VARCHAR(50),
    AVATAR VARCHAR(30),
    FLG2FATT SMALLINT DEFAULT 0,
    FLGPWDLESS SMALLINT DEFAULT 0 NOT NULL,
    FLGPASSWORD SMALLINT DEFAULT 1 NOT NULL,
    CODLINGUA VARCHAR(2) DEFAULT 'IT',
    FLGSUPER SMALLINT DEFAULT 0,
    FLGADMINCONFIG SMALLINT DEFAULT 0,
    CELLULARE VARCHAR(15),
    PAGDEF VARCHAR(50),
    JSON_METADATA BLOB SUB_TYPE 1
);

ALTER TABLE UTENTI_CONFIG ADD CONSTRAINT PK_UTENTI_CONFIG PRIMARY KEY (CODUTE);

CREATE TABLE UTENTI_PWD (
    CODUTE INTEGER NOT NULL,
    PWD VARCHAR(255)
);

ALTER TABLE UTENTI_PWD ADD CONSTRAINT PK_UTENTI_PWD PRIMARY KEY (CODUTE);

CREATE TABLE UTENTI_OLDPWD (
    CODUTE INTEGER NOT NULL,
    OLDPWD VARCHAR(255)
);

ALTER TABLE UTENTI_OLDPWD ADD CONSTRAINT PK_UTENTI_OLDPWD PRIMARY KEY (CODUTE);

CREATE TABLE UTENTI_GDPR (
    CODUTE INTEGER NOT NULL,
    DATACC DATE NOT NULL,
    GDPR VARCHAR(2000)
);

ALTER TABLE UTENTI_GDPR ADD CONSTRAINT PK_UTENTI_GDPR PRIMARY KEY (CODUTE, DATACC);

CREATE TABLE RUOLI (
    CODRUO INTEGER NOT NULL,
    DESRUO VARCHAR(30)
);

ALTER TABLE RUOLI ADD CONSTRAINT PK_RUOLI PRIMARY KEY (CODRUO);

CREATE TABLE MENU_GRP (
    CODGRP VARCHAR(1) NOT NULL,
    DESGRP VARCHAR(100),
    FLGENABLED SMALLINT DEFAULT 0,
    ORDINE SMALLINT DEFAULT 0,
    NOMECAMPO VARCHAR(20)
);

ALTER TABLE MENU_GRP ADD CONSTRAINT PK_MENU_GRP PRIMARY KEY (CODGRP);

CREATE TABLE MENU_TIPI (
    CODTIP VARCHAR(1) NOT NULL,
    DESTIP VARCHAR(20)
);

ALTER TABLE MENU_TIPI ADD CONSTRAINT PK_MENU_TIPI PRIMARY KEY (CODTIP);

CREATE TABLE MENU (
    CODMNU VARCHAR(20) NOT NULL,
    DESMNU VARCHAR(100),
    CODGRP VARCHAR(1) NOT NULL,
    FLGENABLED INTEGER DEFAULT 0,
    ICON VARCHAR(50),
    ORDINE SMALLINT,
    CODTIP VARCHAR(1),
    PAGINA VARCHAR(50),
    RIFMENU VARCHAR(20),
    NOTE VARCHAR(1000)
);

ALTER TABLE MENU ADD CONSTRAINT PK_MENU PRIMARY KEY (CODMNU);

CREATE TABLE ABILITAZIONI (
    CODUTE INTEGER NOT NULL,
    CODMNU VARCHAR(20) NOT NULL,
    TIPABI SMALLINT DEFAULT 0
);

ALTER TABLE ABILITAZIONI ADD CONSTRAINT PK_ABILITAZIONI PRIMARY KEY (CODUTE, CODMNU);

CREATE TABLE RUOLI_MNU (
    CODRUO INTEGER NOT NULL,
    CODMNU VARCHAR(20) NOT NULL,
    TIPABI SMALLINT
);

ALTER TABLE RUOLI_MNU ADD CONSTRAINT PK_RUOLI_MNU PRIMARY KEY (CODRUO, CODMNU);

CREATE TABLE UTENTI_RUOLI (
    CODUTE INTEGER NOT NULL,
    CODRUO INTEGER NOT NULL
);

ALTER TABLE UTENTI_RUOLI ADD CONSTRAINT PK_UTENTI_RUOLI PRIMARY KEY (CODUTE, CODRUO);

CREATE TABLE FILTRI_TIPO (
    TIPFIL SMALLINT NOT NULL,
    DESFIL VARCHAR(20),
    FLDFIL VARCHAR(20),
    FLGENABLED SMALLINT DEFAULT 1 NOT NULL
);

ALTER TABLE FILTRI_TIPO ADD CONSTRAINT PK_FILTRI_TIPO PRIMARY KEY (TIPFIL);

CREATE TABLE FILTRI (
    CODUTE INTEGER NOT NULL,
    PROG INTEGER NOT NULL,
    TIPFIL SMALLINT
);

ALTER TABLE FILTRI ADD CONSTRAINT PK_FILTRI PRIMARY KEY (CODUTE, PROG);

CREATE TABLE SSO_PROVIDER (
    PROVIDER VARCHAR(64) CHARACTER SET ASCII NOT NULL,
    DESCRIZIONE VARCHAR(160) CHARACTER SET UTF8 NOT NULL,
    FLGATTIVO SMALLINT DEFAULT 1 NOT NULL,
    DATINS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NOTA VARCHAR(500) CHARACTER SET UTF8
);

ALTER TABLE SSO_PROVIDER ADD CONSTRAINT PK_SSO_PROVIDER PRIMARY KEY (PROVIDER);

CREATE TABLE UTENTI_IDENTITA_EXT (
    IDNKEY CHAR(64) CHARACTER SET ASCII NOT NULL,
    CODUTE INTEGER NOT NULL,
    PROVIDER VARCHAR(64) CHARACTER SET ASCII NOT NULL,
    SUBJECT VARCHAR(512) CHARACTER SET UTF8 NOT NULL,
    FLGATTIVO SMALLINT DEFAULT 1 NOT NULL,
    DATINS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATLASTLOGIN TIMESTAMP,
    DATDISATT TIMESTAMP,
    NOTA VARCHAR(500) CHARACTER SET UTF8
);

ALTER TABLE UTENTI_IDENTITA_EXT ADD CONSTRAINT PK_UTENTI_IDENTITA_EXT PRIMARY KEY (IDNKEY);

CREATE TABLE ACCESSI_2FA (
    CHALLENGE_ID VARCHAR(64) CHARACTER SET ASCII NOT NULL,
    CODUTE INTEGER NOT NULL,
    EMAIL VARCHAR(254) CHARACTER SET UTF8 NOT NULL,
    AUTHMODE VARCHAR(12) CHARACTER SET ASCII NOT NULL,
    IDNKEY VARCHAR(64) CHARACTER SET ASCII,
    CODEHASH VARCHAR(64) CHARACTER SET ASCII NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    SENT_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATTEMPTS SMALLINT DEFAULT 0 NOT NULL,
    SENDS SMALLINT DEFAULT 1 NOT NULL
);

ALTER TABLE ACCESSI_2FA ADD CONSTRAINT PK_ACCESSI_2FA PRIMARY KEY (CHALLENGE_ID);

ALTER TABLE ABILITAZIONI ADD CONSTRAINT FK_ABILITAZIONI_1 FOREIGN KEY (CODMNU) REFERENCES MENU (CODMNU);

ALTER TABLE MENU ADD CONSTRAINT FK_MENU_1 FOREIGN KEY (CODGRP) REFERENCES MENU_GRP (CODGRP);

ALTER TABLE MENU ADD CONSTRAINT FK_MENU_2 FOREIGN KEY (CODTIP) REFERENCES MENU_TIPI (CODTIP);

ALTER TABLE UTENTI_RUOLI ADD CONSTRAINT FK_RUOLI FOREIGN KEY (CODRUO) REFERENCES RUOLI (CODRUO) ON DELETE CASCADE;

ALTER TABLE UTENTI_RUOLI ADD CONSTRAINT FK_UTENTI FOREIGN KEY (CODUTE) REFERENCES UTENTI (CODUTE) ON DELETE CASCADE;

ALTER TABLE UTENTI_IDENTITA_EXT ADD CONSTRAINT FK_UTEIDEXT_UTENTE FOREIGN KEY (CODUTE) REFERENCES UTENTI (CODUTE) ON DELETE CASCADE;

ALTER TABLE UTENTI_IDENTITA_EXT ADD CONSTRAINT FK_UTEIDEXT_PROVIDER FOREIGN KEY (PROVIDER) REFERENCES SSO_PROVIDER (PROVIDER);

ALTER TABLE ACCESSI_2FA ADD CONSTRAINT FK_ACCESSI_2FA_USER FOREIGN KEY (CODUTE) REFERENCES UTENTI (CODUTE) ON DELETE CASCADE;

ALTER TABLE SSO_PROVIDER ADD CONSTRAINT CK_SSO_PROVIDER_ATTIVO CHECK (FLGATTIVO IN (0, 1));

ALTER TABLE UTENTI_IDENTITA_EXT ADD CONSTRAINT CK_UTEIDEXT_ATTIVO CHECK (FLGATTIVO IN (0, 1));

CREATE INDEX IDX_UTEIDEXT_CODUTE ON UTENTI_IDENTITA_EXT (CODUTE);

CREATE INDEX IDX_UTEIDEXT_PROVIDER ON UTENTI_IDENTITA_EXT (PROVIDER);

CREATE INDEX IDX_ACCESSI_2FA_USER ON ACCESSI_2FA (CODUTE, CREATED_AT);

CREATE INDEX IDX_ACCESSI_2FA_EXP ON ACCESSI_2FA (EXPIRES_AT);

CREATE SEQUENCE GEN_UTENTI_ID;

CREATE SEQUENCE GEN_RUOLI_ID;

SET TERM ^ ;

CREATE TRIGGER UTENTI_BI FOR UTENTI ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.CODUTE IS NULL) THEN NEW.CODUTE = GEN_ID(GEN_UTENTI_ID, 1); NEW.DATINS = CURRENT_TIMESTAMP; END^

CREATE TRIGGER RUOLI_BI FOR RUOLI ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.CODRUO IS NULL) THEN NEW.CODRUO = GEN_ID(GEN_RUOLI_ID, 1); END^

CREATE TRIGGER FILTRI_BI0 FOR FILTRI ACTIVE BEFORE INSERT POSITION 0
AS DECLARE VARIABLE TOT INTEGER; BEGIN IF (NEW.PROG IS NULL) THEN BEGIN SELECT COALESCE(MAX(PROG), 0) FROM FILTRI WHERE CODUTE = NEW.CODUTE INTO :TOT; NEW.PROG = TOT + 1; END END^

CREATE TRIGGER UTENTI_GDPR_BI0 FOR UTENTI_GDPR ACTIVE BEFORE INSERT POSITION 0
AS BEGIN NEW.DATACC = CURRENT_TIMESTAMP; UPDATE UTENTI SET FLGGDPR = 1, DATGDPR = CURRENT_TIMESTAMP WHERE CODUTE = NEW.CODUTE; END^

SET TERM ; ^
