/******************************************************************************/
/*            Generated by IBExpert 2010.01.06 31/07/2026 11:50:48            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE '192.168.0.236:G:\Esgest\Dati\ACCESSi_LIM_TEST.gdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_RUOLI_ID;
SET GENERATOR GEN_RUOLI_ID TO 6;

CREATE GENERATOR GEN_UTENTI_ID;
SET GENERATOR GEN_UTENTI_ID TO 275;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE ABILITAZIONI (
    CODUTE  INTEGER NOT NULL,
    CODMNU  CHAR(20) NOT NULL,
    TIPABI  SMALLINT DEFAULT 0
);


CREATE TABLE FILTRI (
    CODUTE       INTEGER NOT NULL,
    PROG         INTEGER NOT NULL,
    NUMREP       INTEGER,
    IDXPERS      INTEGER,
    CODCLISUPER  INTEGER,
    CODAGE       INTEGER,
    CODCLICOL    INTEGER,
    CODCLIENTI   CHAR(255),
    TIPFIL       SMALLINT,
    CODDIP       INTEGER,
    IDXPOS       SMALLINT,
    CODVET       INTEGER
);


CREATE TABLE FILTRI_TIPO (
    TIPFIL      SMALLINT NOT NULL,
    DESFIL      CHAR(20),
    FLDFIL      CHAR(20),
    FLGENABLED  SMALLINT DEFAULT 1 NOT NULL
);


CREATE TABLE MENU (
    CODMNU      CHAR(20) NOT NULL,
    DESMNU      CHAR(100),
    CODGRP      CHAR(1) NOT NULL,
    FLGENABLED  INTEGER DEFAULT 0,
    ICON        CHAR(50),
    ORDINE      SMALLINT,
    CODTIP      CHAR(1),
    PAGINA      CHAR(50),
    RIFMENU     CHAR(20),
    NOTE        VARCHAR(1000)
);


CREATE TABLE MENU_GRP (
    CODGRP      CHAR(1) NOT NULL,
    DESGRP      CHAR(100),
    FLGENABLED  SMALLINT DEFAULT 0,
    ORDINE      SMALLINT DEFAULT 0,
    NOMECAMPO   CHAR(20)
);


CREATE TABLE MENU_TIPI (
    CODTIP  CHAR(1) NOT NULL,
    DESTIP  CHAR(20)
);


CREATE TABLE PARAMETRI (
    CODPAR  VARCHAR(15) NOT NULL,
    DESPAR  VARCHAR(255),
    NOTE    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    GRUPPO  CHAR(20)
);


CREATE TABLE RUOLI (
    CODRUO  INTEGER NOT NULL,
    DESRUO  CHAR(30)
);


CREATE TABLE RUOLI_MNU (
    CODRUO  INTEGER NOT NULL,
    CODMNU  CHAR(20) NOT NULL,
    TIPABI  SMALLINT
);


CREATE TABLE UTENTI (
    CODUTE        INTEGER NOT NULL,
    USRNAME       CHAR(100),
    FLGGDPR       SMALLINT DEFAULT 0,
    DATGDPR       DATE,
    DATINS        DATE,
    DATSCAPWD     DATE,
    DATLASTLOGIN  DATE,
    STAREG        SMALLINT DEFAULT 0,
    KEYREG        CHAR(100)
);


CREATE TABLE UTENTI_CONFIG (
    CODUTE          INTEGER NOT NULL,
    COGNOME         CHAR(50),
    NOME            CHAR(50),
    AVATAR          CHAR(30),
    FLG2FATT        SMALLINT DEFAULT 0,
    CAUMOV          CHAR(100),
    CODLINGUA       CHAR(2) DEFAULT 'IT',
    FLGSUPER        SMALLINT DEFAULT 0,
    FLGMOP          SMALLINT DEFAULT 0,
    FLGPIANA        SMALLINT DEFAULT 0,
    FLGADDETTI      SMALLINT DEFAULT 0,
    FLGOSPITI       SMALLINT DEFAULT 0,
    CELLULARE       CHAR(15),
    FLGPIANARFID    SMALLINT DEFAULT 0,
    FLGCONTA        SMALLINT DEFAULT 0,
    FLGCUBI         SMALLINT DEFAULT 0,
    FLGCICLPASS     SMALLINT DEFAULT 0,
    PAGDEF          CHAR(50),
    FLGCLIENTI      SMALLINT,
    FLGFORNITORI    SMALLINT,
    FLGLISTINI      SMALLINT,
    FLGTASK         SMALLINT,
    FLGINVENTARI    SMALLINT DEFAULT 0,
    FLGDIPENDENTI   SMALLINT DEFAULT 0,
    RAGSOCCLI       VARCHAR(100),
    JSON_METADATA   BLOB SUB_TYPE 1 SEGMENT SIZE 16384,
    FLGADMINCONFIG  SMALLINT DEFAULT 0
);


CREATE TABLE UTENTI_GDPR (
    CODUTE  INTEGER NOT NULL,
    DATACC  DATE NOT NULL,
    GDPR    VARCHAR(2000)
);


CREATE TABLE UTENTI_OLDPWD (
    CODUTE  INTEGER NOT NULL,
    OLDPWD  CHAR(255)
);


CREATE TABLE UTENTI_PWD (
    CODUTE  INTEGER NOT NULL,
    PWD     CHAR(255)
);


CREATE TABLE UTENTI_RUOLI (
    CODUTE  INTEGER NOT NULL,
    CODRUO  INTEGER NOT NULL
);




/******************************************************************************/
/*                                Primary Keys                                */
/******************************************************************************/

ALTER TABLE ABILITAZIONI ADD CONSTRAINT PK_ABILITAZIONI PRIMARY KEY (CODUTE, CODMNU);
ALTER TABLE FILTRI ADD CONSTRAINT PK_FILTRI PRIMARY KEY (CODUTE, PROG);
ALTER TABLE FILTRI_TIPO ADD CONSTRAINT PK_FILTRI_TIPO PRIMARY KEY (TIPFIL);
ALTER TABLE MENU ADD CONSTRAINT PK_MENU PRIMARY KEY (CODMNU);
ALTER TABLE MENU_GRP ADD CONSTRAINT PK_MENU_GRP PRIMARY KEY (CODGRP);
ALTER TABLE MENU_TIPI ADD CONSTRAINT PK_MENU_TIPI PRIMARY KEY (CODTIP);
ALTER TABLE PARAMETRI ADD CONSTRAINT PK_PARAMETRI PRIMARY KEY (CODPAR);
ALTER TABLE RUOLI ADD CONSTRAINT PK_RUOLI PRIMARY KEY (CODRUO);
ALTER TABLE RUOLI_MNU ADD CONSTRAINT PK_RUOLI_MNU PRIMARY KEY (CODRUO, CODMNU);
ALTER TABLE UTENTI ADD CONSTRAINT PK_UTENTI PRIMARY KEY (CODUTE);
ALTER TABLE UTENTI_CONFIG ADD CONSTRAINT PK_UTENTI_CONFIG PRIMARY KEY (CODUTE);
ALTER TABLE UTENTI_GDPR ADD CONSTRAINT PK_UTENTI_GDPR PRIMARY KEY (CODUTE, DATACC);
ALTER TABLE UTENTI_OLDPWD ADD CONSTRAINT PK_UTENTI_OLDPWD PRIMARY KEY (CODUTE);
ALTER TABLE UTENTI_PWD ADD CONSTRAINT PK_UTENTI_PWD PRIMARY KEY (CODUTE);
ALTER TABLE UTENTI_RUOLI ADD PRIMARY KEY (CODUTE, CODRUO);


/******************************************************************************/
/*                                Foreign Keys                                */
/******************************************************************************/

ALTER TABLE ABILITAZIONI ADD CONSTRAINT FK_ABILITAZIONI_1 FOREIGN KEY (CODMNU) REFERENCES MENU (CODMNU);
ALTER TABLE MENU ADD CONSTRAINT FK_MENU_1 FOREIGN KEY (CODGRP) REFERENCES MENU_GRP (CODGRP);
ALTER TABLE MENU ADD CONSTRAINT FK_MENU_2 FOREIGN KEY (CODTIP) REFERENCES MENU_TIPI (CODTIP);
ALTER TABLE UTENTI_RUOLI ADD CONSTRAINT FK_RUOLI FOREIGN KEY (CODRUO) REFERENCES RUOLI (CODRUO) ON DELETE CASCADE;
ALTER TABLE UTENTI_RUOLI ADD CONSTRAINT FK_UTENTI FOREIGN KEY (CODUTE) REFERENCES UTENTI (CODUTE) ON DELETE CASCADE;


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: FILTRI_BI0 */
CREATE TRIGGER FILTRI_BI0 FOR FILTRI
ACTIVE BEFORE INSERT POSITION 0
AS
 declare variable tot integer;
begin
   if (new.prog is null) then begin
      select max(prog) from filtri where codute= new.codute into :tot;
      if (tot=0 or (tot is null) ) then tot=0;
      new.prog = tot+1;
   end
end
^


/* Trigger: RUOLI_BI */
CREATE TRIGGER RUOLI_BI FOR RUOLI
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODRUO IS NULL) THEN
    NEW.CODRUO = GEN_ID(GEN_RUOLI_ID,1);
END
^


/* Trigger: UTENTI_BD0 */
CREATE TRIGGER UTENTI_BD0 FOR UTENTI
ACTIVE BEFORE DELETE POSITION 0
AS
begin
     delete from utenti_config where codute=old.codute;
     delete from utenti_oldpwd where codute=old.codute;
     delete from utenti_pwd where codute=old.codute;
     delete from abilitazioni where codute=old.codute;
     delete from filtri where codute=old.codute;
end
^


/* Trigger: UTENTI_BI */
CREATE TRIGGER UTENTI_BI FOR UTENTI
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.codute is null) then
    new.codute = gen_id(gen_utenti_id,1);

    new.datins = current_timestamp;  
end
^


/* Trigger: UTENTI_GDPR_BI0 */
CREATE TRIGGER UTENTI_GDPR_BI0 FOR UTENTI_GDPR
ACTIVE BEFORE INSERT POSITION 0
AS
begin
     new.datacc = current_timestamp;
     update utenti set flggdpr=1, datgdpr=current_timestamp
     where codute=new.codute;
end
^


/* Trigger: UTENTI_PWD_BIU0 */
CREATE TRIGGER UTENTI_PWD_BIU0 FOR UTENTI_PWD
ACTIVE BEFORE INSERT POSITION 0
AS     
begin     
    update or insert into UTENTI_OLDPWD (CODUTE,OLDPWD) values (new.CODUTE,new.PWD);
end
^


/* Trigger: UTENTI_PWD_BIU1 */
CREATE TRIGGER UTENTI_PWD_BIU1 FOR UTENTI_PWD
ACTIVE BEFORE INSERT OR UPDATE POSITION 1
AS
begin
     update utenti set datscapwd=current_timestamp+90 where codute=new.codute;
end
^


SET TERM ; ^



/******************************************************************************/
/*                            Fields descriptions                             */
/******************************************************************************/

DESCRIBE FIELD CODMNU TABLE ABILITAZIONI
'codice del menu abilitato';

DESCRIBE FIELD TIPABI TABLE ABILITAZIONI
'codice di abilitazione';

DESCRIBE FIELD NUMREP TABLE FILTRI
'numero reparto';

DESCRIBE FIELD IDXPERS TABLE FILTRI
'idx personale';

DESCRIBE FIELD CODCLISUPER TABLE FILTRI
'codice cliente padre (codcli di esgest)';

DESCRIBE FIELD CODAGE TABLE FILTRI
'codice agente';

DESCRIBE FIELD CODCLICOL TABLE FILTRI
'codice cliente collegato (codcli di esgest)';

DESCRIBE FIELD CODCLIENTI TABLE FILTRI
'lista dei clienti da visualizzare (codcli di esgest)';

DESCRIBE FIELD TIPFIL TABLE FILTRI
'codice del tipo di filtro';

DESCRIBE FIELD CODDIP TABLE FILTRI
'codice dipendente esgest';

DESCRIBE FIELD IDXPOS TABLE FILTRI
'idx della postazione nella tabella ANTESSE_POS di PROLAV';

DESCRIBE FIELD CODVET TABLE FILTRI
'CODICE DEL VETTORE DA INSERIRE SE COME FILTRO HA 30';

DESCRIBE FIELD TIPFIL TABLE FILTRI_TIPO
'codice tipo filtro';

DESCRIBE FIELD DESFIL TABLE FILTRI_TIPO
'descrizione del tipo filtro';

DESCRIBE FIELD FLDFIL TABLE FILTRI_TIPO
'campo di riferimento';

DESCRIBE FIELD CODMNU TABLE MENU
'codice menu';

DESCRIBE FIELD DESMNU TABLE MENU
'desrizione menu';

DESCRIBE FIELD CODGRP TABLE MENU
'codice gruppo menu';

DESCRIBE FIELD FLGENABLED TABLE MENU
'menu abilitato';

DESCRIBE FIELD ICON TABLE MENU
'icona da visualizzare del menu';

DESCRIBE FIELD ORDINE TABLE MENU
'ordine visualizzazione nel sottomenu';

DESCRIBE FIELD CODTIP TABLE MENU
'indica se menu o altro';

DESCRIBE FIELD PAGINA TABLE MENU
'pagina da aprire';

DESCRIBE FIELD CODGRP TABLE MENU_GRP
'codice gruppo menu';

DESCRIBE FIELD DESGRP TABLE MENU_GRP
'descrizione gruppo';

DESCRIBE FIELD FLGENABLED TABLE MENU_GRP
'gruppo abilitato';

DESCRIBE FIELD ORDINE TABLE MENU_GRP
'ordine visualizzazione gruppo nel menu';

DESCRIBE FIELD NOMECAMPO TABLE MENU_GRP
'nome del campo flag sulla tabella utenti_config';

DESCRIBE FIELD CODTIP TABLE MENU_TIPI
'codice tipo menu';

DESCRIBE FIELD DESTIP TABLE MENU_TIPI
'descrizione tipo menu';

DESCRIBE FIELD CODRUO TABLE RUOLI
'codice ruolo';

DESCRIBE FIELD DESRUO TABLE RUOLI
'descrizione ruolo';

DESCRIBE FIELD CODRUO TABLE RUOLI_MNU
'codice ruolo';

DESCRIBE FIELD CODMNU TABLE RUOLI_MNU
'codice menu';

DESCRIBE FIELD TIPABI TABLE RUOLI_MNU
'tipo abilitazione';

DESCRIBE FIELD CODUTE TABLE UTENTI
'codice utente';

DESCRIBE FIELD USRNAME TABLE UTENTI
'username, mail di registrazione';

DESCRIBE FIELD FLGGDPR TABLE UTENTI
'flag accettazione GDPR';

DESCRIBE FIELD DATGDPR TABLE UTENTI
'data accettazione';

DESCRIBE FIELD DATINS TABLE UTENTI
'data inserimento';

DESCRIBE FIELD DATSCAPWD TABLE UTENTI
'data scadenza password';

DESCRIBE FIELD DATLASTLOGIN TABLE UTENTI
'data ultimo login';

DESCRIBE FIELD STAREG TABLE UTENTI
'codice stato di registrazione';

DESCRIBE FIELD KEYREG TABLE UTENTI
'chiave di registrazione';

DESCRIBE FIELD CODUTE TABLE UTENTI_CONFIG
'codice utente';

DESCRIBE FIELD COGNOME TABLE UTENTI_CONFIG
'cognome';

DESCRIBE FIELD NOME TABLE UTENTI_CONFIG
'nome';

DESCRIBE FIELD AVATAR TABLE UTENTI_CONFIG
'immagine del profilo';

DESCRIBE FIELD FLG2FATT TABLE UTENTI_CONFIG
'se 1 autenticazione a 2 fattori';

DESCRIBE FIELD CAUMOV TABLE UTENTI_CONFIG
'causali di movimento che puo vedere';

DESCRIBE FIELD CODLINGUA TABLE UTENTI_CONFIG
'codice lingua di default';

DESCRIBE FIELD FLGSUPER TABLE UTENTI_CONFIG
'super utente admin';

DESCRIBE FIELD FLGMOP TABLE UTENTI_CONFIG
'se 1 abilitato a vedere i MOP';

DESCRIBE FIELD FLGPIANA TABLE UTENTI_CONFIG
'se 1 abilitato a vedere la biancheria piana';

DESCRIBE FIELD FLGADDETTI TABLE UTENTI_CONFIG
'se 1 abilitato a vedere gli addetti/personale';

DESCRIBE FIELD FLGOSPITI TABLE UTENTI_CONFIG
'se 1 abilitato a vedere gli ospiti';

DESCRIBE FIELD CELLULARE TABLE UTENTI_CONFIG
'cellulare se autenticazione a 2 fattori';

DESCRIBE FIELD FLGPIANARFID TABLE UTENTI_CONFIG
'se 1 abilitato a vedere la biancheria piana chippata';

DESCRIBE FIELD FLGCONTA TABLE UTENTI_CONFIG
'se 1 abilitato a vedere la contabilita';

DESCRIBE FIELD FLGCUBI TABLE UTENTI_CONFIG
'se 1 abilitato a vedere i cubi';

DESCRIBE FIELD FLGCICLPASS TABLE UTENTI_CONFIG
'se 1 abilitato al ciclo passivo';

DESCRIBE FIELD PAGDEF TABLE UTENTI_CONFIG
'pagina di default dopo il login';

DESCRIBE FIELD FLGINVENTARI TABLE UTENTI_CONFIG
'se 1 abilitato a creare/vedere gli inventari';

DESCRIBE FIELD FLGDIPENDENTI TABLE UTENTI_CONFIG
'se 1 abiliato per gestione dipendenti';

DESCRIBE FIELD FLGADMINCONFIG TABLE UTENTI_CONFIG
'flag utente configuratore dei menu amministratore';

DESCRIBE FIELD CODUTE TABLE UTENTI_OLDPWD
'codice utente';

DESCRIBE FIELD OLDPWD TABLE UTENTI_OLDPWD
'password gia utilizzata';

DESCRIBE FIELD CODUTE TABLE UTENTI_PWD
'codice utente';

DESCRIBE FIELD PWD TABLE UTENTI_PWD
'password';

